site_name: Tech Notes
site_description: Personal computer science technical notes and documentation
site_author: Marco Vedovati
repo_url: https://github.com/marcov/tech-notes
site_url: https://docs.sba.lat
docs_dir: docs

theme: alabaster
#theme: readthedocs
#theme: mkdocs

#pages:
#- Home:
#  - Overview: 'README.md'
#  - ACME Documentation: 'ACME.md'
#- Installation:
#  - ACME Installation: 'installation/ACME.md'
#- Configuration:
#  - ACME Configuration: 'configuration/ACME.md'
#- Development:
#  - ACME Coding Conventions: 'development/ACME.md'
#- References: 'references.md'
#
#google_analytics: ['UA-#########-#', 'docs.sba.lat']
